# script generated by model to calculate grand total of ad budgets

import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv('advertising_budget_and_sales.csv')

# Calculate the grand total of TV, radio, and newspaper ad budgets
grand_total = df['TV Ad Budget ($)'].sum() + df['Radio Ad Budget ($)'].sum() + df['Newspaper Ad Budget ($)'].sum()

print(f"The grand total of all TV, radio, and newspaper ad budgets is: ${grand_total:.2f}")